### PR TITLE
Add new MaraPool and EMCD coinbase tags

### PR DESCRIPTION
**Pull request by guybrushino**
https://mempool.space/it/tx/36a6a80642e3ff6d325f49fd0fa5b05020795919ff15090d7237682204a81a05

### CODE REVIEW

**Comment by 0xB10C** [comment]
Thank you for the PR. The commit with the new Mara tag looks good. Do you have a link to the block for the emcd tag too? I guess just emcd.io would be enough. The 989X might change between blocks?

**Comment by guybrushino** [comment]
You're right

https://mempool.space/it/block/000000000000000000017173a28dc9f35cab8c58aa91aea2d23b1c6bec9c07d3
https://mempool.space/it/block/00000000000000000005777b28461cb8512c7072a2cc778054e1ecbab428cde6

image

**Comment by 0xB10C** [comment]
Can you fixup the last emcd commit? Otherwise, I'd be happy to do it.

**Comment by 0xB10C** [comment]
Ups, didn't mean to close this by squashing. Will reopen!

**Comment by 0xB10C** [comment]
a

**Comment by 0xB10C** [comment]
Seems like I can't squash on your branch. Will have to do it in another PR.

**Pull request closed without merging**
